[build]
builder = "nixpacks"

[build.nixpacks]
aptPkgs = []

[deploy]
startCommand = "node dist/main"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
